/**
* Edemam Nutrition Analysis - KnowYourCarbs
* Made for app KnowYourCarbs for an API Description.
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package hu.bme.aut.jokes.data.network.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 * @param uri Ontology identifier
 */
@JsonClass(generateAdapter = true)
data class NutrientInfoDTO (
    /* Ontology identifier */
    @Json(name = "uri")
    val uri: NutrientChildDTO? = null
)

