/**
* Edemam Nutrition Analysis - KnowYourCarbs
* Made for app KnowYourCarbs for an API Description.
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package hu.bme.aut.jokes.data.network.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 * @param uri Ontology identifier
 * @param yield ingredients (array of strings)
 * @param calories Total energy, kcal
 * @param totalNutrients Total nutrients
 * @param totalDaily % daily value
 * @param dietLabels 
 * @param healthLabels 
 */
@JsonClass(generateAdapter = true)
data class RecipeResponseDTO (
    /* Ontology identifier */
    @Json(name = "uri")
    val uri: kotlin.String? = null,
    /* ingredients (array of strings) */
    @Json(name = "yield")
    val yield: kotlin.Int? = null,
    /* Total energy, kcal */
    @Json(name = "calories")
    val calories: java.math.BigDecimal? = null,
    /* Total nutrients */
    @Json(name = "totalNutrients")
    val totalNutrients: NutrientInfoDTO? = null,
    /* % daily value */
    @Json(name = "totalDaily")
    val totalDaily: NutrientInfoDTO? = null,
    @Json(name = "dietLabels")
    val dietLabels: RecipeResponseDTO.DietLabels? = null,
    @Json(name = "healthLabels")
    val healthLabels: RecipeResponseDTO.HealthLabels? = null
) {

    /**
    * 
    * Values: BALANCED,HIGH_MINUS_PROTEIN,HIGH_MINUS_FIBER,LOW_MINUS_FAT,LOW_MINUS_CARB,LOW_MINUS_SODIUM
    */
    
    enum class DietLabels(val value: kotlin.String){
        @Json(name = "balanced") BALANCED("balanced"),
        @Json(name = "high-protein") HIGH_MINUS_PROTEIN("high-protein"),
        @Json(name = "high-fiber") HIGH_MINUS_FIBER("high-fiber"),
        @Json(name = "low-fat") LOW_MINUS_FAT("low-fat"),
        @Json(name = "low-carb") LOW_MINUS_CARB("low-carb"),
        @Json(name = "low-sodium") LOW_MINUS_SODIUM("low-sodium");
    }
    /**
    * 
    * Values: VEGAN,VEGETARIAN,DAIRY_MINUS_FREE,LOW_MINUS_SUGAR,LOW_MINUS_FAT_MINUS_ABS,SUGAR_MINUS_CONSCIOUS,FAT_FREE,GLUTEN_FREE,WHEAT_FREE
    */
    
    enum class HealthLabels(val value: kotlin.String){
        @Json(name = "vegan") VEGAN("vegan"),
        @Json(name = "vegetarian") VEGETARIAN("vegetarian"),
        @Json(name = "dairy-free") DAIRY_MINUS_FREE("dairy-free"),
        @Json(name = "low-sugar") LOW_MINUS_SUGAR("low-sugar"),
        @Json(name = "low-fat-abs") LOW_MINUS_FAT_MINUS_ABS("low-fat-abs"),
        @Json(name = "sugar-conscious") SUGAR_MINUS_CONSCIOUS("sugar-conscious"),
        @Json(name = "fat free") FAT_FREE("fat free"),
        @Json(name = "gluten free") GLUTEN_FREE("gluten free"),
        @Json(name = "wheat free") WHEAT_FREE("wheat free");
    }
}

